### ISSUE TITLE
what does vvp mean in this code?

### ISSUE THREAD

**Issue by yetniek** [jinlinyi/PerspectiveFields#14]
Hi,

https://github.com/jinlinyi/PerspectiveFields/blob/f439f30b4f1e7588c9bdb9c72aa238da075fbc9d/perspective2d/utils/panocam.py#L500

I think that the meaning of vvp is a vertical vanishing point, but in the reference link above, I assume that the meaning of vvp is a view vector point. Is this the right way to think? I thought this because the vvp function already exists in another code. So what does vvp mean in this code?

**Comment by jinlinyi** [comment]
Hi, this is still the vertical vanishing point. There are some duplicated codes in this file. Sorry for the confusion.
