### ISSUE TITLE
Monitoring Perspective Transform and Data Visualization During Training

### ISSUE THREAD

**Issue by yetniek** [jinlinyi/PerspectiveFields#15]
Hello, 

I would like to check this during training to see if perspective_transform is working well for the image, gravity, and latitude data. Each class has different visualization features. I think i can use a visualization in Performer_heads.py, but I don't know how to use it. Can you please give me some advice? 

Thanks.

**Comment by jinlinyi** [comment]
Hi,

We log all visualizations to [tensorboard](https://pytext.readthedocs.io/en/master/visualize_your_model.html). In your training directory, launch tensorboard and you should be able to visualize the training loss, latitude map and up vectors, etc.
