### ISSUE TITLE
Stanford2D3D and Tartanair Eval

### ISSUE THREAD

**Issue by veichta** [jinlinyi/PerspectiveFields#20]
Hi, 

Thank you for this awesome work. We are currently trying to reproduce the evaluations on the stanford2d3d as well as the tartanair benchmarks. I have added the following to `perspective2d/data/datasets/builtin.py`:

```
SPLITS_STANFORD2D3D = {
    "stanford2d3d_test": ("./datasets/stanford2d3d_test", "./datasets/stanford2d3d_test.json"),
}

def register_stanford2d3d(dataset_name, json_file, image_root):
    DatasetCatalog.register(dataset_name, lambda: load_stanford2d3d_json(json_file, image_root))
    MetadataCatalog.get(dataset_name).set(
        json_file=json_file,
        image_root=image_root,
        evaluator_type="perspective",
        ignore_label=-1,
    )

for key, (img_root, anno_file) in SPLITS_STANFORD2D3D.items():
    register_stanford2d3d(key, anno_file, img_root)
```

I have downloaded the datasets (test.zip, test.json) from the polybox link and the corresponding weights. If I run the eval using the following command:

```
python -W ignore demo/test_warp.py \
--dataset stanford2d3d_test \
--output ./exps/persnet_360_cities_test \
--config-file ./models/cvpr2023.yaml \
--opts MODEL.WEIGHTS ./models/cvpr2023.pth
```

I get the following results which are not what we would expect if we compare the results to Table 1:

```
up_errs mean: 12.18
up_errs median: 2.18
up_errs %<5: 82.11
lati_errs mean: 6.99
lati_errs median: 3.40
lati_errs %<5: 69.48
12.18 & 2.18 & 82.11 & 6.99 & 3.40 & 69.48 \\
```

Is there anything I am doing wrong in this eval? Could you maybe provide clear steps in order to evaluate the cvpr weights as well as the new ParamNet weights on these benchmarks?

**Comment by jinlinyi** [comment]
Hi Alexander,

Thank you for pointing this issue out. The script is different from what we used for evaluation. I will fix it soon.

**Comment by jinlinyi** [comment]
Hi Alexander, 

The issue should be fixed now. Please let me know if it works for you now.

**Comment by veichta** [comment]
Thank you for the quick fix! It seems to work now.

Just to confirm, are these the kind of numbers we would expect from the paramnet_360cities_edina_rpf model on stanford2d3d?

```
['roll', 'pitch', 'vfov']
5.99 & 2.87 & 9.07 & 3.23 & 9.43 & 7.77 & \\
up_errs median: 3.55
up_errs %<5: 67.08
lati_errs median: 3.83
lati_errs %<5: 63.35
3.55 & 67.08 & 3.83 & 63.35 \\
```

**Comment by jinlinyi** [comment]
Yes, I get the same result.
