### ISSUE TITLE
How to retrieve elevation information of the camera?

### ISSUE THREAD

**Issue by Nucleon729** [jinlinyi/PerspectiveFields#23]
Hi there,
thanks so much for this amazing tool.

I'm trying to retrieve the elevation information of the camera during inference, but it only gives me vFov, Roll, Pitch...

do you have any idea?

**Comment by jinlinyi** [comment]
![image](https://github.com/jinlinyi/PerspectiveFields/assets/33358154/cff8b9a2-8981-4576-bb99-1a779c4e65dc)
Is Pitch what you are looking for?

**Comment by Nucleon729** [comment]
Pitch is part of it, but for some reason I need other parameter.

The issue I have is when I rebuild the camera in a 3D space and reproject the reference photo, the horizon line is always offset, and I have to manually shift the camera lens in the y-direction to bring the horizon line back to where it should be.

Or more simply the height of the camera/sensor relative to the ground..

**Comment by jinlinyi** [comment]
Hi, 

The horizon location in the image is not dependent on the camera height relative to the ground. Can you give me an example of your problem?

**Comment by Nucleon729** [comment]
Hi,

Thank you for your quick response.

I apologize if I did not explain properly what I'm trying to achieve: I'm trying to use the camera informations provided by your amazing tool, in order to recreate the scene in Blender 3D.

So in my 3D scene, the higher the camera is positioned above the ground, the more of the scene below the horizonPlane becomes visible, causing the horizon to appear higher within the image frame. This relationship between camera height and horizon position is a crucial concept in photography and perspective analysis.

That said, I'm totally able to obtain camera rotations, focal length, and distortion, but I'm still missing height information, or at least the coordinates of the horizon to get a more accurate camera position.


I've added 2 images to explain my issue:

On the first image, I have setup the camera height position at 2m:
<img width="738" alt="Screenshot 2024-04-27 at 10 06 37" src="https://github.com/jinlinyi/PerspectiveFields/assets/112477930/1ff0b6ca-9c28-467f-9897-13ce01feccfb">

and I'm adjusting the camera height position at 5.72m:
<img width="733" alt="Screenshot 2024-04-27 at 10 06 29" src="https://github.com/jinlinyi/PerspectiveFields/assets/112477930/6222ffe7-6f7f-4e5a-b027-4db09b5613a2">

you can see that the we horizon line moved, and it reveals new faces of the cubes.

**Comment by jinlinyi** [comment]
Hi, 

Here's the function to calculate horizon line from camera parameters, note that it is not dependent on camera height. The variable `elevation` is camera `pitch` angle. 
https://github.com/jinlinyi/PerspectiveFields/blob/d54be737d6eacfb9d39a2b7079a494924b45bb6c/perspective2d/utils/panocam.py#L336-L348

Alternatively, we can figure out the horizon location from vanishing points, I sketch the plot below: 
<img width="1552" alt="Screenshot 2024-04-27 at 11 13 10 AM" src="https://github.com/jinlinyi/PerspectiveFields/assets/33358154/eb4518e5-b811-477a-98f6-37033f0408f4">

The horizon lines remain consistent across different camera heights, as illustrated in the plot. To understand why, follow these steps:

- Identify Vanishing Points of horizontal lines: Start by finding the vanishing points for each set of parallel lines that are also parallel to the ground, marked by solid lines in the diagram.

- Draw the Horizon Line: Connect the vanishing points to get the horizon, marked as a dashed line. Theoretically, it should remain constant regardless of the camera's height. Please refer to section 8.6.2 Vanishing lines of the [Multiview Geometry book](https://www.robots.ox.ac.uk/~vgg/hzbook/).
The horizon line is the vanishing line of horizontal planes.
<img width="730" alt="image" src="https://github.com/jinlinyi/PerspectiveFields/assets/33358154/544dd4e5-093e-426e-bc7d-cad9932b4071">

**Comment by Nucleon729** [comment]
Brillant!  I think getRelativeHorizonLineFromAngles() will do the job!

thank you very much for your help
