### ISSUE TITLE
Questions for Making a Comparison!

### ISSUE THREAD

**Issue by TWJianNuo** [jinlinyi/PerspectiveFields#3]
Thank you for your great work! We would like to compare our method with yours, but we have a few questions:

1. Did you train and test the model reported in Table 3 only on the GSV dataset, or did you include additional data?
2. Would it be possible for you to share the checkpoint of the model that you trained on a larger scale of the data?
3. We noticed that to recover the focal length with the estimated value, you multiply it by the height (or width) of the image. Is this correct?
4. Similarly, we saw that to recover the central point with the estimated value, you multiply it by the height (or width) of the image and add half of the image height (or width). Is this correct?

Thanks!

**Comment by jinlinyi** [comment]
Hi

1. For Table 3, the network is only trained on GSV. 
2. [Here](https://www.dropbox.com/s/czqrepqe7x70b7y/cvpr2023.pth) is the checkpoint of the PerspectiveNet trained on 360Cities dataset. We are working on training the ParamNet on the larger scale dataset.
3 & 4. Yes. The focal length and principal point location are relative to the image size, so to get them in pixel space, we multiply them by the image height.

**Comment by TWJianNuo** [comment]
Thank you for your really really prompt response!

If it is convenient for you, would it be possible to double-check the conversion script between the network output and intrinsic for resized 320x320 images? 

`

    def recover_intrinsic(pred, imh, imgw):
      assert imh == 320
      assert imw == 320
      cx, cy = pred['pred_rel_cx'].cpu().item() * imgw + imgw / 2, pred['pred_rel_cy'].cpu().item() * imh + imh / 2
  
      fovv_rad = np.radians(pred['pred_general_vfov'].cpu().item())
      focal = imh / 2 / np.tan(fovv_rad / 2)
  
      intrinsic = np.eye(3)
  
      intrinsic[0, 0] = focal
      intrinsic[1, 1] = focal
      intrinsic[0, 2] = cx
      intrinsic[1, 2] = cy
  
      return intrinsic


`

**Comment by jinlinyi** [comment]
If you assume uncentered principal point, please use `general_vfov_to_focal` to solve for focal length from `general_vfov`. 
https://github.com/jinlinyi/PerspectiveFields/blob/4cb5c56d5b91662de51de7e950cebc5fa88efd98/perspectiveField/perspective2d/utils/utils.py#L28-L40
```python
focal = general_vfov_to_focal(pred['pred_rel_cx'], pred['pred_rel_cy'], imh, pred['pred_general_vfov'], degree=True)
```

**Comment by TWJianNuo** [comment]
I see, and thanks for your patience and detailed response!

I got one last question. 
We do not have a paramnet model trained on the City360 dataset right?
Only a perspective field network is trained on that dataset, according to the given checkpoint.

**Comment by jinlinyi** [comment]
Yes, that is correct so far. But we are working on training the ParamNet on a more diverse dataset such as 360Cities so please stay tuned.

**Comment by TWJianNuo** [comment]
I see, Thanks!
