### ISSUE TITLE
data_load

### ISSUE THREAD

**Issue by yzh1527** [jinlinyi/PerspectiveFields#4]
Thank you for your great work! We would like to ask you a few questions:
In panocam.py, what's the meaning of horizon  vvp  absvvp in get_up()

**Comment by jinlinyi** [comment]
Hi, sorry for the confusion. We will document this in the next version.

The `horizon` array holds two values that correspond to the vertical positions of the horizon line on the left and right edges of the image, respectively. These positions are expressed as a fraction of the image height (0.0 means the top of the image, and 1.0 means the bottom). 

`vvp` stands for the Vertical Vanishing Point, which is the vanishing point for the vertical lines. `absvvp` is in pixels, `vvp` is normalized by the image size, see https://github.com/jinlinyi/PerspectiveFields/blob/4cb5c56d5b91662de51de7e950cebc5fa88efd98/perspectiveField/perspective2d/utils/panocam.py#L381

This function plots the vertical vanishing point and horizon line on an image. 
https://github.com/jinlinyi/PerspectiveFields/blob/4cb5c56d5b91662de51de7e950cebc5fa88efd98/perspectiveField/perspective2d/utils/panocam.py#L535
