### ISSUE TITLE
How do I get a original GSV dataset?

### ISSUE THREAD

**Issue by yetniek** [jinlinyi/PerspectiveFields#5]
Hi! Thanks for good work 👍 

I want to make a crop gsv dataset that you uploaded in `train.md`. (google_street_view_191210) To that end, I think we can use the function in `perspective2d/utils/panocam.py`, but I confuse about which function to use. Can you tell me?

Also, did you guys download and use the GSV dataset from the official site below when you brought it? 
If you used it, there are various files here, which one did you use?  Or did you use StreetLearn Dataset? 

1) http://www.cs.ucf.edu/~aroshan/index_files/Dataset_PitOrlManh/ 
2) https://sites.google.com/view/streetlearn/dataset

I looked it up and found several places that offer gsv datasets, but the information I have is a little different, so I don't know which dataset to use. So I wonder where you guys got the original google street view dataset.  
and Is the implementation environment Ubuntu? There are a lot of conflicts when I try to do it in a Windows ;(

I'll be waiting for your answer! Thank you

**Comment by jinlinyi** [comment]
Hi, 

We got the dataset from CTRL-C https://github.com/jwlee-vcl/CTRL-C. 

During training, we randomly crop the GSV original data that we have. See code below https://github.com/jinlinyi/PerspectiveFields/blob/4cb5c56d5b91662de51de7e950cebc5fa88efd98/perspectiveField/perspective2d/data/perspective_transforms.py#L317-L332

Our code is tested on Ubuntu.

**Comment by yetniek** [comment]
I asked the CTRL-C authors if they could update the dataset link, and they did! 
Access is now possible. thank you!
