### ISSUE TITLE
360 Cities model weights

### ISSUE THREAD

**Issue by myronzbrown** [jinlinyi/PerspectiveFields#9]
Thanks for this great work and for open sourcing your code. I'm running some tests on a variety of hand-held and security camera images that I know are well-calibrated, and I'm using your GSV model weights. Roll and pitch predictions look reasonable, and the perspective field visualizations look good, but FOV predictions do not match known values well. I tried with both square cropped and uncropped images. I do not expect street-level GSV to generalize well, or at least that was my impression when running CTRL-C last year. Do you plan to also release the weights trained with 360 Cities? I'm hoping that such a diverse dataset may allow the model to generalize well, but I'm also still trying to wrap my head around FOV being predictable from a single image without making simplifying assumptions (e.g., I think GSV 360 photos are collected at a fixed height, which would probably help a lot if only testing on GSV). I'm excited to try the 360 Cities weights if it's possible to release them. I tried using the CVPR weights, but it doesn't look like it predicts all of the parameters. Or maybe I just did something wrong? Really cool paper. Thanks for your time.

**Comment by jinlinyi** [comment]
Hi Myron, 

Thank you so much for your interest in our project. We have released our checkpoint trained on 360cities. 
`NEW:Paramnet-360Cities-edina-centered`: https://www.dropbox.com/s/z2dja70bgy007su/paramnet_360cities_edina_rpf.pth
`config_file`: `models/paramnet_360cities_edina_rpf.yaml`

`NEW:Paramnet-360Cities-edina-uncentered`: 
https://www.dropbox.com/s/nt29e1pi83mm1va/paramnet_360cities_edina_rpfpp.pth
`config_file`: `models/paramnet_360cities_edina_rpfpp.yaml`

It is currently not well documented in our GitHub repo yet but we are working on improving the codebase. 
You can download the checkpoint from the above link or directly try your images on our hugging face demo https://huggingface.co/spaces/jinlinyi/PerspectiveFields

**Comment by myronzbrown** [comment]
Thank you for such a quick response. The weights work better than I expected with my images. So far, results are reasonable except when I zoom to << 30 degree FOV where it was not trained. Really nice.
